[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"

ignore = [
  # proc-macro-error is a transitive dependency of a number of dependencies, 
  # this is allowed for now til the ecosystem migrates away
  "RUSTSEC-2024-0370",
  # instant is dependency of notify and tao, until those remove instant this
  # will be allowed
  "RUSTSEC-2024-0384",
  # blocked on portable-pty migrating away from serial
  "RUSTSEC-2017-0008",
]

[licenses]
version = 2
private = { ignore = true }
# licenses should only be approved licences by Amazon, if you
# are unsure please contact a maintainer otherwise other licences
# will be denied
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC-PDDC",
  "CC0-1.0",
  "ISC",
  "MIT",
  "MPL-2.0",
  "OpenSSL",
  "Unicode-3.0",
  "Zlib",
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[bans]
multiple-versions = "allow"
wildcards = "deny"
allow-wildcard-paths = true
highlight = "all"

[bans.workspace-dependencies]
duplicates = "allow"
include-path-dependencies = true
unused = "deny"

[[bans.deny]]
name = "openssl"

[[bans.deny]]
name = "git2"

[[bans.deny]]
name = "tempdir"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
